spring:
  application:
    name: ShopAssistant
  datasource:
    url: jdbc:postgresql://8.163.27.12:5432/jchatmind
    username: muzhiyuan
    password: 20031121zzh.
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.qq.com
    port: 587
    username: 2685922758@qq.com
    password: xxx # 邮箱授权码
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  ai:
    deepseek:
      api-key: xxx
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
    zhipuai:
      api-key: your-api-key
      base-url: https://open.bigmodel.cn/api/paas
      chat:
        options:
          model: glm-4.6
mybatis:
  type-aliases-package: com.xmu.ShopAssistant.model.entity
  mapper-locations: classpath:mapper/*.xml
  type-handlers-package: com.xmu.ShopAssistant.typehandler

document:
  storage:
    base-path: ./data/documents

pdf:
  font:
    path: C:/Windows/Fonts/msyh.ttc   # 中文字体路径，不配置则自动探测系统字体
    ttc-index: 0                        # TTC 字体集合索引（默认 0）
